# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TiffSlider
                                 A QGIS plugin
 It slides Tiffs.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-12-04
        copyright            : (C) 2024 by RKIW
        email                : idgaf@dimanet.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

from .tiff_slider import TiffSlider
from .resources import *

def classFactory(iface):
    return TiffSlider(iface)
